name: PHPUnit

env:
  COMPOSER_VERSION: '2'
  COMPOSER_CACHE: '${{ github.workspace }}/.composer-cache'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # We claim to support from 7.2+, but Mockery supports from 7.3+ only
        php: ['7.3', '7.4', '8.0', '8.1']
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Cache Directories
        run: |
          composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"

      - name: Prepare Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE }}
          key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ env.COMPOSER_VERSION }}-

      - name: Set PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install NPM and Composer Dependencies
        run: npm install

      - name: Run Build Task
        run: npm run build

      - name: PHPUnit
        run: npm run test:unit
